/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_eg10_ffmpeg_NDKFFmpeg */

#ifndef _Included_com_tz_ffmpeg_NDKFFmpeg
#define _Included_com_tz_ffmpeg_NDKFFmpeg
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_sun_eg10_NDKFFmpeg_callFFmpegTestConfig
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_sun_eg10_NDKFFmpeg_callFFmpegOldReadInfo
(JNIEnv *, jobject,jstring);

JNIEXPORT void JNICALL Java_com_sun_eg10_NDKFFmpeg_callFFmpegNewReadInfo
(JNIEnv *, jobject,jstring);

JNIEXPORT void JNICALL Java_com_sun_eg10_NDKFFmpeg_callFFmpegOldDecode
(JNIEnv *, jobject,jstring,jstring);

JNIEXPORT void JNICALL Java_com_sun_eg10_NDKFFmpeg_callFFmpegNewDecode
(JNIEnv *, jobject,jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
